name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
      # 缓存Playwright浏览器二进制，加速后续构建
      - name: Cache Playwright binaries
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-pw-1.60.0
      - name: Ensure browsers are installed
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install chromium --with-deps"
      - name: Run tests
#        env:
#          APP_USERNAME: ${{ secrets.TEST_USERNAME }}
#          APP_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: mvn test -Dheadless=true -Dusername="${{ secrets.TEST_USERNAME }}" -Dpassword="${{ secrets.TEST_PASSWORD }}"
      # 获取gh-pages历史（用于allure趋势图）
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      # Allure生成报告
      - name: Allure Report with history
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results
      # 部署静态报告到Github Pages
      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          publish_branch: gh-pages
